INSERT INTO POSTS(USER_ID, BODY) VALUES (1, 'TEST TO DELETE');
COMMIT;

UPDATE POSTS
SET BODY = 'TO DELETE'
WHERE ID = 15;
COMMIT;
SELECT*FROM POSTS;

DELETE FROM POSTS
WHERE ID =15;
COMMIT;